CosmosClient: CosmosClient Class Reference
CosmosClient Class Reference
Cosmos Client Implements a stateful Cosmos Client using Cosmos SQL-API via REST.
#include <azure-cosmos-restcl.hpp>
Public Member Functions
CosmosClient ()
Default constructor.
const nlohmann::json & configuration ()
Gets the current configuration object.
CosmosClient & configure (const nlohmann::json &src={}) noexcept(false)
Re-configure the client. This will invoke the discoverRegions to populate the available regions and sets the primary write/read locations. If the source is empty (no arguments) then the current configuration is returned. Avoid repeated invocations! This method may throw if the underling call to discoverRegions fails.
CosmosResponseType discoverRegions ()
Discover the Regions for the current base Uri This method is invoked by the configuration method.
CosmosResponseType listDatabases ()
List all databases for the given service Refer to https://docs.microsoft.com/en-us/rest/api/documentdb/documentdb-resource-uri-syntax-for-rest.
CosmosResponseType listCollections (const std::string &dbName)
List the collections for the given database.
CosmosIterableResponseType listDocuments (const std::string &dbName, const std::string &collName, const std::string &continuationToken)
List documents for the given database and collection.
CosmosResponseType create (const std::string &dbName, const std::string &collName, const nlohmann::json &doc)
Create an entity in documentdb using the json object as the payload.
CosmosResponseType upsert (const std::string &dbName, const std::string &collName, const nlohmann::json &doc)
Insert or Update existing document for the given id.
CosmosResponseType update (const std::string &dbName, const std::string &collName, const std::string &docId, const std::string &pkId)
Update existing document.
uint32_t remove (const std::string &dbName, const std::string &collName, const std::string &docId, const std::string &pkId)
Removes the document given the docId and pkId https://docs.microsoft.com/en-us/rest/api/documentdb/delete-a-document.
CosmosIterableResponseType query (const std::string &dbName, const std::string &collName, const std::string &pkId, const std::string &queryStatement, const nlohmann::json &params={}, const std::string &continuationToken={})
Performs a query and continues an existing query if the continuation token exists CAUTION: If your query yields dozens or hundreds or thousands of documents, this method currently does not offer "streaming" or callbacks. It continues until the server reports no-more-continuation and returns the documents in a single response json. Memory and timing can be massive!
CosmosResponseType find (const std::string &dbName, const std::string &collName, const std::string &docId, const std::string &pkId)
Find a given document by id.
Static Public Attributes
static const std::string CosmosClientUserAgentString {"SiddiqSoft.CosmosClient/0.1.0"}
This is the string used in the User-Agent header.
Protected Attributes
nlohmann::json m_config
configuration object updated/merged with the client object
nlohmann::json serviceSettings
Service Settings saved from discoverRegion.
std::atomic_bool m_isConfigured {false}
Used to signal first-time configuration.
WinHttpRESTClient RestClient {CosmosClientUserAgentString}
The REST client is initialized with the user agent.
CosmosConnection Cnxn {}
The connection object stores the Primary, Secondary connection strings as well as the read/write locations for the given Azure location.
Friends
void to_json (nlohmann::json &dest, const CosmosClient &src)
JSON serializer helper for CosmosClient.
Detailed Description
Cosmos Client Implements a stateful Cosmos Client using Cosmos SQL-API via REST.
Uses the REST API and SQL API model. https://docs.microsoft.com/en-us/rest/api/cosmos-db/common-tasks-using-the-cosmosdb-rest-api
See also
Samples are here: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-cpp-get-started
Documentation is here: https://docs.microsoft.com/en-us/rest/api/documentdb/documentdb-resource-uri-syntax-for-rest
Constructor & Destructor Documentation
CosmosClient()
CosmosClient () inline
Default constructor.
Member Function Documentation
configuration()
const nlohmann::json & configuration () inline
Gets the current configuration object.
Returns
Configuration json
References CosmosClient::m_config.
Referenced by TEST().
configure()
CosmosClient & configure (const nlohmann::json & src = {}) inline noexcept
Re-configure the client. This will invoke the discoverRegions to populate the available regions and sets the primary write/read locations. If the source is empty (no arguments) then the current configuration is returned. Avoid repeated invocations! This method may throw if the underling call to discoverRegions fails.
Parameters
src A valid json object must comply with the defaults. If empty, the current configuration is returned without any changes. Must have the following elements: {"connectionStrings": ["primary-connection-string"], "primaryKeyNames": ["field-name-of-partition-id"]}
Returns
Self
Referenced by TEST().
create()
CosmosResponseType create (const std::string & dbName, const std::string & collName, const nlohmann::json & doc) inline
Create an entity in documentdb using the json object as the payload.
Parameters
dbName Database name
collName Collection name
doc The document must include the id and the partition key.
Returns
status code and the created document as returned by Cosmos
See also
Example over at https://docs.microsoft.com/en-us/rest/api/documentdb/create-a-document
References CosmosClient::Cnxn, CosmosConnection::current(), CosmosEndpoint::currentWriteUri(), CosmosEndpoint::Key, CosmosClient::m_config, and CosmosClient::RestClient.
Referenced by TEST().
discoverRegions()
CosmosResponseType discoverRegions () inline
Discover the Regions for the current base Uri This method is invoked by the configuration method.
Returns
Tuple of the status code and the json response (or empty)
References CosmosClient::Cnxn, CosmosConnection::current(), CosmosEndpoint::currentReadUri(), and CosmosClient::RestClient.
Referenced by TEST().
find()
CosmosResponseType find (const std::string & dbName, const std::string & collName, const std::string & docId, const std::string & pkId) inline
Find a given document by id.
Parameters
dbName The database name
collName The collection name
docId The unique id
pkId Partition id
Returns
CosmosResponseType - StatusCode and a single JSON document corresponding to the docId
sample document
{
  "__pk": "siddiqsoft.com",
  "_attachments": "attachments/",
  "_etag": "\"0c0124ff-0000-0400-0000-612ecb520000\"",
  "_rid": "RP0wAM6H+R6g1FIAAAAADQ==",
  "_self": "dbs/RP0wAA==/colls/RP0wAM6H+R4=/docs/RP0wAM6H+R6g1FIAAAAADQ==/",
  "_ts": 1630456658,
  "id": "azure-cosmos-restcl.16304566579088218",
  "source": "basic_tests.exe",
  "ttl": 360
}
Remarks
We do not modify or abstract the contents.
References CosmosClient::Cnxn, CosmosConnection::current(), CosmosEndpoint::currentWriteUri(), CosmosEndpoint::Key, CosmosClient::m_config, and CosmosClient::RestClient.
listCollections()
CosmosResponseType listCollections (const std::string & dbName) inline
List the collections for the given database.
Parameters
dbName Database name
Returns
The json document from Cosmos contains the collections for the given
References CosmosClient::Cnxn, CosmosConnection::current(), CosmosEndpoint::currentReadUri(), CosmosEndpoint::Key, CosmosClient::m_config, and CosmosClient::RestClient.
Referenced by TEST().
listDatabases()
CosmosResponseType listDatabases () inline
List all databases for the given service Refer to https://docs.microsoft.com/en-us/rest/api/documentdb/documentdb-resource-uri-syntax-for-rest.
Returns
The json document response or error code
References CosmosClient::Cnxn, CosmosConnection::current(), CosmosEndpoint::currentReadUri(), CosmosEndpoint::Key, CosmosClient::m_config, and CosmosClient::RestClient.
Referenced by TEST().
listDocuments()
CosmosIterableResponseType listDocuments (const std::string & dbName, const std::string & collName, const std::string & continuationToken) inline
List documents for the given database and collection.
Parameters
dbName The database name
collName The collectio nname
[in,out] continuationToken Optional continuation token. This is used with the value x-ms-continuation. This variable is updated with the value from x-ms-continuation header value. The client must check and invoke the method repeatedly until this variable is empty. to page through the query response.
Returns
CosmosIterableResponseType contains the status code and if succesfull the contents and optionally the continuation token.
Remarks
The call returns 100 items and you must invoke the method again with the continuation token to fetch the next 100 items. It is not wise to use this method as it is expensive. Use the [find](find) method or the more flexible [query] method.
Sample logic for continuation
siddiqsoft::CosmosIterableResponseType irt {};
// This is your destination container; note that the first element is null in this example
nlohmann::json                         allDocs = nlohmann::json::array();
// This is the running count of the total
uint32_t                               allDocsCount {};
// First, we query for all items that match our criteria (source=__func__)
do {
    irt = cc.query(dbName,
                   collectionName,
                   "*",
                   "SELECT * FROM c WHERE contains(c.source, @v1)",
                   {{{"name", "@v1"}, {"value", std::format("{}-", getpid())}}},
                   irt.continuationToken);
    if (200 == irt.statusCode &&
        irt.document.contains("Documents") &&
        !irt.document.at("Documents").is_null())
    {
        // Append to the current container
        allDocs.insert(allDocs.end(),                     // dest
                       irt.document["Documents"].begin(), // from
                       irt.document["Documents"].end());
        allDocsCount += irt.document.value("_count", 0);
    }
} while (!irt.continuationToken.empty());
References CosmosClient::Cnxn, CosmosConnection::current(), CosmosEndpoint::currentReadUri(), CosmosEndpoint::Key, CosmosClient::m_config, and CosmosClient::RestClient.
Referenced by TEST().
query()
CosmosIterableResponseType query (const std::string & dbName, const std::string & collName, const std::string & pkId, const std::string & queryStatement, const nlohmann::json & params = {}, const std::string & continuationToken = {}) inline
Performs a query and continues an existing query if the continuation token exists CAUTION: If your query yields dozens or hundreds or thousands of documents, this method currently does not offer "streaming" or callbacks. It continues until the server reports no-more-continuation and returns the documents in a single response json. Memory and timing can be massive!
Parameters
dbName Database name
collName Collection name
pkId Primary key id: may be *, or the partition id value
queryStatement The SQL API query string.
params Optional json array with name-value objects.
continuationToken Optional continuation token. This is used with the value x-ms-continuation to page through the query response.
Returns
CosmosIterableResponseType
See also
CosmosIterableResponseType for details on the sample multi-query.
https://docs.microsoft.com/en-us/rest/api/cosmos-db/q
https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-getting-started
Remarks
The response is paged so you will need to combine the results into delivering to the user a single json with array of Documents object and _count.
Output Sample
{
   "Documents": [
      {
         "__pk": "odd.siddiqsoft.com",
         "_attachments": "attachments/",
         "_etag": "\"7e0141d3-0000-0400-0000-612ec6f10000\"",
         "_rid": "RP0wAM6H+R7-8VEAAAAAAQ==",
         "_self": "dbs/RP0wAA==/colls/RP0wAM6H+R4=/docs/RP0wAM6H+R7-8VEAAAAAAQ==/",
         "_ts": 1630455537,
         "i": 1,
         "id": "azure-cosmos-restcl.16304555368341392",
         "odd": true,
         "source": "23676-SiddiqSoft.CosmosClient/0.1.0",
         "ttl": 360
      },
      ...
      ...
   ],
   "_count": 2
}
remove()
uint32_t remove (const std::string & dbName, const std::string & collName, const std::string & docId, const std::string & pkId) inline
Removes the document given the docId and pkId https://docs.microsoft.com/en-us/rest/api/documentdb/delete-a-document.
Parameters
dbName Cosmos Database name
collName Cosmos Collection Name
docId Unique document Id
pkId The partition Id
Returns
Status code with empty json
Remarks
The remove operation returns no data beyond the status code.
References CosmosClient::Cnxn, CosmosConnection::current(), CosmosEndpoint::currentWriteUri(), CosmosEndpoint::Key, CosmosClient::m_config, and CosmosClient::RestClient.
Referenced by TEST().
update()
CosmosResponseType update (const std::string & dbName, const std::string & collName, const std::string & docId, const std::string & pkId) inline
Update existing document.
Parameters
dbName Database name
collName Collection name
docId Unique document id
pkId Partition key
Returns
Status code and Json document for the docId
References CosmosClient::Cnxn, CosmosConnection::current(), CosmosEndpoint::currentWriteUri(), CosmosEndpoint::Key, CosmosClient::m_config, and CosmosClient::RestClient.
upsert()
CosmosResponseType upsert (const std::string & dbName, const std::string & collName, const nlohmann::json & doc) inline
Insert or Update existing document for the given id.
Parameters
dbName Database name
collName Collection name
doc The document must include the id and the partition key.
Returns
status code and the created document as returned by Cosmos The status code is 201 when the document has been created The status code 200 represents a document that has been updated.
References CosmosClient::Cnxn, CosmosConnection::current(), CosmosEndpoint::currentWriteUri(), CosmosEndpoint::Key, CosmosClient::m_config, and CosmosClient::RestClient.
Friends And Related Function Documentation
to_json
void to_json (nlohmann::json & dest, const CosmosClient & src) friend
JSON serializer helper for CosmosClient.
Parameters
dest Output json object
src Reference to a CosmosClient instance
Member Data Documentation
Cnxn
CosmosConnection Cnxn {} protected
The connection object stores the Primary, Secondary connection strings as well as the read/write locations for the given Azure location.
Referenced by CosmosClient::create(), CosmosClient::discoverRegions(), CosmosClient::find(), CosmosClient::listCollections(), CosmosClient::listDatabases(), CosmosClient::listDocuments(), CosmosClient::remove(), TEST(), CosmosClient::update(), and CosmosClient::upsert().
CosmosClientUserAgentString
const std::string CosmosClientUserAgentString {"SiddiqSoft.CosmosClient/0.1.0"} inline static
This is the string used in the User-Agent header.
Referenced by TEST().
m_config
nlohmann::json m_config protected
Initial value:
{
                {"_typever", CosmosClientUserAgentString},
                {"apiVersion", "2018-12-31"},
                {"connectionStrings", {}},
                {"partitionKeyNames", {}}
        }
configuration object updated/merged with the client object
Referenced by CosmosClient::configuration(), CosmosClient::create(), CosmosClient::find(), CosmosClient::listCollections(), CosmosClient::listDatabases(), CosmosClient::listDocuments(), CosmosClient::remove(), CosmosClient::update(), and CosmosClient::upsert().
m_isConfigured
std::atomic_bool m_isConfigured {false} protected
Used to signal first-time configuration.
RestClient
WinHttpRESTClient RestClient {CosmosClientUserAgentString} protected
The REST client is initialized with the user agent.
Referenced by CosmosClient::create(), CosmosClient::discoverRegions(), CosmosClient::find(), CosmosClient::listCollections(), CosmosClient::listDatabases(), CosmosClient::listDocuments(), CosmosClient::remove(), CosmosClient::update(), and CosmosClient::upsert().
serviceSettings
nlohmann::json serviceSettings protected
Service Settings saved from discoverRegion.
Referenced by TEST().
The documentation for this class was generated from the following file:
C:/Users/maas/source/repos/siddiqsoft/CosmosClient/src/azure-cosmos-restcl.hpp