CosmosClient: C:/Users/maas/source/repos/siddiqsoft/CosmosClient/tests/test.cpp File Reference
test.cpp File Reference
#include "gtest/gtest.h"
#include <thread>
#include <functional>
#include <chrono>
#include "nlohmann/json.hpp"
#include "../src/azure-cosmos-restcl.hpp"
Functions
TEST (CosmosConnection, test1_n)
Test the serializers and cast operators.
TEST (CosmosConnection, test2_n)
Tests the serializers. Compiliation will fail for malformed/missing serializers.
TEST (CosmosConnection, rotateConnection_1)
Test rotate between primary and secondary connection.
TEST (CosmosConnection, rotateConnection_2)
Check the rotate method with single connection.
TEST (CosmosEndpoint, test1_n)
Test serializers and cast for the CosmosEndpoint object no extra read/write locations.
TEST (CosmosEndpoint, test2_n)
Test serializers and cast operators for CosmosEndpoint object with additional read/write locations.
TEST (CosmosClient, example1)
Example code Declare the instance, configure and create a document with only three lines! The code here is based on configuration and dynamic fetching for the database, collection and regions.
TEST (CosmosClient, configure_Defaults)
Test the configuration defaults Checks that we match the changes to the configuration defaults in code against the documentation and client tests.
TEST (CosmosClient, configure_check_json)
Checks the CosmosClient to_json has a consistent output.
TEST (CosmosClient, configure_1)
Test to check call to configure will pull in the serviceSettings. The serviceSettings contains information about the service as reported by call to discoverRegions Here we perform a configure and check the responses obtained from the Azure service.
TEST (CosmosClient, discoverRegions)
TEST (CosmosClient, discoverRegions_BadPrimary)
TEST (CosmosClient, listDatabases)
TEST (CosmosClient, listCollections)
TEST (CosmosClient, listDocuments)
Tests the listDocuments with a limit of 7 iterations.
TEST (CosmosClient, listDocuments_top100)
Invokes listDocuments without continuation.
TEST (CosmosClient, createDocument)
Test create document API. Removes the document after completion. Requires the environment variables.
TEST (CosmosClient, createDocument_MissingId)
Test create document with missing "id" field in the document.
TEST (CosmosClient, createDocument_MissingPkId)
Test create document with missing partition key field in the document.
TEST (CosmosClient, findDocument)
Test find API.
TEST (CosmosClient, upsertDocument)
Test upsert API.
TEST (CosmosClient, queryDocument)
Test query API.
Function Documentation
TEST() [1/22]
TEST (CosmosClient , configure_1)
Test to check call to configure will pull in the serviceSettings. The serviceSettings contains information about the service as reported by call to discoverRegions Here we perform a configure and check the responses obtained from the Azure service.
NOTE: The serviceSettings is protected and this test declares the macro COSMOSCLIENT_TESTING_MODE to enable public access during testing stage only.
References CosmosClient::configure().
TEST() [2/22]
TEST (CosmosClient , configure_check_json)
Checks the CosmosClient to_json has a consistent output.
TEST() [3/22]
TEST (CosmosClient , configure_Defaults)
Test the configuration defaults Checks that we match the changes to the configuration defaults in code against the documentation and client tests.
References CosmosClient::configuration().
TEST() [4/22]
TEST (CosmosClient , createDocument)
Test create document API. Removes the document after completion. Requires the environment variables.
References CosmosClient::configure().
TEST() [5/22]
TEST (CosmosClient , createDocument_MissingId)
Test create document with missing "id" field in the document.
References CosmosClient::configure().
TEST() [6/22]
TEST (CosmosClient , createDocument_MissingPkId)
Test create document with missing partition key field in the document.
References CosmosClient::configure().
TEST() [7/22]
TEST (CosmosClient , discoverRegions)
References CosmosClient::Cnxn, CosmosClient::configure(), CosmosConnection::current(), CosmosEndpoint::ReadableUris, CosmosClient::serviceSettings, and CosmosEndpoint::WritableUris.
TEST() [8/22]
TEST (CosmosClient , discoverRegions_BadPrimary)
References CosmosClient::Cnxn, CosmosClient::configure(), CosmosClient::discoverRegions(), CosmosResponseType::document, and CosmosConnection::rotate().
TEST() [9/22]
TEST (CosmosClient , example1)
Example code Declare the instance, configure and create a document with only three lines! The code here is based on configuration and dynamic fetching for the database, collection and regions.
References CosmosClient::configure(), CosmosClient::create(), CosmosClient::listCollections(), CosmosClient::listDatabases(), and CosmosClient::remove().
TEST() [10/22]
TEST (CosmosClient , findDocument)
Test find API.
References CosmosClient::configure().
TEST() [11/22]
TEST (CosmosClient , listCollections)
References CosmosClient::configure(), CosmosClient::listCollections(), and CosmosClient::listDatabases().
TEST() [12/22]
TEST (CosmosClient , listDatabases)
References CosmosClient::configure(), and CosmosClient::listDatabases().
TEST() [13/22]
TEST (CosmosClient , listDocuments)
Tests the listDocuments with a limit of 7 iterations.
References CosmosClient::configure(), CosmosClient::listCollections(), CosmosClient::listDatabases(), and CosmosClient::listDocuments().
TEST() [14/22]
TEST (CosmosClient , listDocuments_top100)
Invokes listDocuments without continuation.
References CosmosClient::configure(), CosmosClient::listCollections(), CosmosClient::listDatabases(), and CosmosClient::listDocuments().
TEST() [15/22]
TEST (CosmosClient , queryDocument)
Test query API.
References CosmosClient::configure(), and CosmosClient::CosmosClientUserAgentString.
TEST() [16/22]
TEST (CosmosClient , upsertDocument)
Test upsert API.
References CosmosClient::configure().
TEST() [17/22]
TEST (CosmosConnection , rotateConnection_1)
Test rotate between primary and secondary connection.
References CosmosConnection::PrimaryConnection, and CosmosConnection::SecondaryConnection.
TEST() [18/22]
TEST (CosmosConnection , rotateConnection_2)
Check the rotate method with single connection.
References CosmosConnection::PrimaryConnection.
TEST() [19/22]
TEST (CosmosConnection , test1_n)
Test the serializers and cast operators.
TEST() [20/22]
TEST (CosmosConnection , test2_n)
Tests the serializers. Compiliation will fail for malformed/missing serializers.
TEST() [21/22]
TEST (CosmosEndpoint , test1_n)
Test serializers and cast for the CosmosEndpoint object no extra read/write locations.
References CosmosEndpoint::BaseUri, CosmosEndpoint::currentReadUri(), CosmosEndpoint::currentWriteUri(), CosmosEndpoint::EncodedKey, CosmosEndpoint::rotateReadUri(), and CosmosEndpoint::rotateWriteUri().
TEST() [22/22]
TEST (CosmosEndpoint , test2_n)
Test serializers and cast operators for CosmosEndpoint object with additional read/write locations.
References CosmosEndpoint::BaseUri, CosmosEndpoint::currentReadUri(), CosmosEndpoint::currentWriteUri(), CosmosEndpoint::EncodedKey, CosmosEndpoint::ReadableUris, CosmosEndpoint::rotateReadUri(), CosmosEndpoint::rotateWriteUri(), and CosmosEndpoint::WritableUris.