CosmosClient: CosmosConnection Struct Reference
CosmosConnection Struct Reference
Represents the Cosmos Cnxn.
#include <azure-cosmos-restcl.hpp>
Public Types
enum class CurrentConnectionIdType : uint16_t { PrimaryConnection = 1 , SecondaryConnection = 2 }
CurrentConnectionIdType.
Public Member Functions
NLOHMANN_JSON_SERIALIZE_ENUM (CurrentConnectionIdType, {{CurrentConnectionIdType::PrimaryConnection, "PrimaryConnection"}, {CurrentConnectionIdType::SecondaryConnection, "SecondaryConnection"}})
Serializer for the internal CurrentConnectionIdType.
CosmosConnection ()=default
Default constructor.
CosmosConnection (const std::basic_string< char > &p, const std::basic_string< char > &s={})
Constructor with Primary and optional Secondary.
CosmosConnection & configure (const nlohmann::json &config)
Configure the Primary and Secondary. Also resets the current connection to the "Primary".
const CosmosEndpoint & current () const
Get the current active connection string.
CosmosConnection & rotate (const uint16_t c=0)
Swaps the current connection by incrementing the current and if we hit past Secondary, we restart at Primary.
Public Attributes
CurrentConnectionIdType CurrentConnectionId {CurrentConnectionIdType::PrimaryConnection}
Current Connection: 0=Not Set 1=Primary 2=Secondary.
CosmosEndpoint Primary {}
The Primary connection string from the Azure Portal.
CosmosEndpoint Secondary {}
The Secondary connection string from the Azure Portal.
Detailed Description
Represents the Cosmos Cnxn.
Member Enumeration Documentation
CurrentConnectionIdType
enum class CurrentConnectionIdType : uint16_t strong
CurrentConnectionIdType.
Enumerator
PrimaryConnection
SecondaryConnection
Constructor & Destructor Documentation
CosmosConnection() [1/2]
CosmosConnection () default
Default constructor.
CosmosConnection() [2/2]
CosmosConnection (const std::basic_string< char > & p, const std::basic_string< char > & s = {}) inline
Constructor with Primary and optional Secondary.
Parameters
p Primary Connection String from Azure portal
s Secondary Connection String from Azure portal
Member Function Documentation
configure()
CosmosConnection & configure (const nlohmann::json & config) inline
Configure the Primary and Secondary. Also resets the current connection to the "Primary".
Parameters
config JSON object with the following elements: connectionStrings array and partitionKeyNames array
Returns
Self
Remarks
Resets the CurrentConnectionId to the Primary(1).
References CosmosConnection::CurrentConnectionId, CosmosConnection::Primary, CosmosEndpoint::ReadableUris, CosmosConnection::Secondary, CosmosConnection::SecondaryConnection, and CosmosEndpoint::WritableUris.
current()
const CosmosEndpoint & current () const inline
Get the current active connection string.
Returns
Cosmos connection string
Reference to the current active Connection Primary/Secondary
References CosmosConnection::CurrentConnectionId, CosmosConnection::Primary, CosmosConnection::Secondary, and CosmosConnection::SecondaryConnection.
Referenced by CosmosClient::create(), CosmosClient::discoverRegions(), CosmosClient::find(), CosmosClient::listCollections(), CosmosClient::listDatabases(), CosmosClient::listDocuments(), CosmosClient::remove(), TEST(), CosmosClient::update(), and CosmosClient::upsert().
NLOHMANN_JSON_SERIALIZE_ENUM()
NLOHMANN_JSON_SERIALIZE_ENUM (CurrentConnectionIdType , {{CurrentConnectionIdType::PrimaryConnection, "PrimaryConnection"}, {CurrentConnectionIdType::SecondaryConnection, "SecondaryConnection"}})
Serializer for the internal CurrentConnectionIdType.
References CosmosConnection::PrimaryConnection, and CosmosConnection::SecondaryConnection.
rotate()
CosmosConnection & rotate (const uint16_t c = 0) inline
Swaps the current connection by incrementing the current and if we hit past Secondary, we restart at Primary.
Parameters
c Maybe 0=Swap 1=Use Primary 2=Use Secondary
Returns
Self
References CosmosConnection::CurrentConnectionId, CosmosEndpoint::EncodedKey, CosmosConnection::PrimaryConnection, CosmosConnection::Secondary, and CosmosConnection::SecondaryConnection.
Referenced by TEST().
Member Data Documentation
CurrentConnectionId
CurrentConnectionIdType CurrentConnectionId {CurrentConnectionIdType::PrimaryConnection}
Current Connection: 0=Not Set 1=Primary 2=Secondary.
Referenced by CosmosConnection::configure(), CosmosConnection::current(), CosmosConnection::rotate(), and siddiqsoft::to_json().
Primary
CosmosEndpoint Primary {}
The Primary connection string from the Azure Portal.
Referenced by CosmosConnection::configure(), CosmosConnection::current(), and siddiqsoft::to_json().
Secondary
CosmosEndpoint Secondary {}
The Secondary connection string from the Azure Portal.
Referenced by CosmosConnection::configure(), CosmosConnection::current(), CosmosConnection::rotate(), and siddiqsoft::to_json().
The documentation for this struct was generated from the following file:
C:/Users/maas/source/repos/siddiqsoft/CosmosClient/src/azure-cosmos-restcl.hpp